datasource:
  password: "localPassword"

# This properties file is loaded into the context when the `local` profile is set
# It will override properties that are specified in the `default` application.properties